### ISSUE TITLE
Error on Android while calling SalesforceSnapIns.determineAvailability

### ISSUE THREAD

**Issue by matscav** [SonoIo/cordova-plugin-salesforce-snapins#6]
Here is the stacktrace:
```
2021-04-19 13:52:40.039 14517-14653/com.my.app E/PluginManager: Uncaught exception from plugin
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.salesforce.android.chat.core.ChatConfiguration$Builder com.salesforce.android.chat.core.ChatConfiguration$Builder.chatUserData(java.util.List)' on a null object reference
        at org.apache.cordova.salesforce.SalesforceSnapInsPlugin.buildLiveAgentChatConfig(SalesforceSnapInsPlugin.java:164)
        at org.apache.cordova.salesforce.SalesforceSnapInsPlugin.execute(SalesforceSnapInsPlugin.java:105)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```
Could you help me?

**Comment by dmitriivikorchuk** [comment]
When initialize use liveAgentChat property instead of liveAgent
https://github.com/SonoIo/cordova-plugin-salesforce-snapins#initializeoptions-success-error

**Comment by dmitriivikorchuk** [comment]
@matscav, when initialize use liveAgentChat property instead of liveAgent
https://github.com/SonoIo/cordova-plugin-salesforce-snapins#initializeoptions-success-error

**Comment by matscav** [comment]
> @matscav, when initialize use liveAgentChat property instead of liveAgent
> https://github.com/SonoIo/cordova-plugin-salesforce-snapins#initializeoptions-success-error

Thank you! It works like a charm.
